http:
  port: "8083"
  
protocol:
    host: "worldtimeapi.org"
    
cloudHub:
     username: "hossana"
     password: "M0910623807$e"
     workers: "1"
     workerType: "Micro"
     environment: "Sandbox"
     muleVersion: "4.3.0"
     applicationName: "worldtime-zone-api"
     
     